name: 部署到 Vercel

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: 安装 Vercel CLI
        run: npm install --global vercel@latest
        
      - name: 拉取 Vercel 环境变量
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: 构建项目
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: 部署到 Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} 